//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipl_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listici
    {
        public int Id { get; set; }
        public string Tekst { get; set; }
        public Nullable<bool> StatusListica { get; set; }
        public Nullable<bool> Provjera { get; set; }
    }
}
