//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dipl_mvc.Models
{
          using System;
          using System.Collections.Generic;
          using System.ComponentModel.DataAnnotations;

          public partial class Utakmice
          {
                    public int Id { get; set; }
                    [Required(ErrorMessage = "  Unesite ime domaæina utakmice")]
                    [Display(Name = "Domaæin: ")]
                    public string Domacin { get; set; }
                    [Required(ErrorMessage = "  Unesite ime gosta utakmice")]
                    [Display(Name = "Gost: ")]
                    public string Gost { get; set; }
                    [Required(ErrorMessage = "  Unesite koeficijent na pobjedu domaæina (npr. 1,5)")]
                    [Range(1.01, 999, ErrorMessage = "  Unesite broj izmeðu 1,01 i 999")]
                    [Display(Name = "Koeficijent na 1: ")]
                    public double Koeficijent_1 { get; set; }
                    [Required(ErrorMessage = "  Unesite koeficijent na neriješen ishod")]
                    [Range(1.01, 999, ErrorMessage = "  Unesite broj izmeðu 1,01 i 999")]
                    [Display(Name = "Koeficijent na X: ")]
                    public double Koeficijent_X { get; set; }
                    [Required(ErrorMessage = "  Unesite koeficijent na pobjedu gosta")]
                    [Range(1.01, 999, ErrorMessage = "  Unesite broj izmeðu 1,01 i 999")]
                    [Display(Name = "Koeficijent na 2: ")]
                    public double Koeficijent_2 { get; set; }
                    [Required(ErrorMessage = "  Unesite koeficijent na pobjedu domaæina ili neriješen ishod")]
                    [Range(1.01, 999, ErrorMessage = "  Unesite broj izmeðu 1,01 i 999")]
                    [Display(Name = "Koeficijent na 1X: ")]
                    public double Koeficijent_1X { get; set; }
                    [Required(ErrorMessage = "  Unesite koeficijent na pobjedu gosta ili neriješen ishod")]
                    [Range(1.01, 999, ErrorMessage = "  Unesite broj izmeðu 1,01 i 999")]
                    [Display(Name = "Koeficijent na X2: ")]
                    public double Koeficijent_X2 { get; set; }
                    [Required(ErrorMessage = "  Unesite koeficijent na pobjedu domaæina ili pobjedu gosta")]
                    [Range(1.01, 999, ErrorMessage = "  Unesite broj izmeðu 1,01 i 999")]
                    [Display(Name = "Koeficijent na 12: ")]
                    public double Koeficijent_12 { get; set; }
                    [Required(ErrorMessage = "  Unesite vrijeme poèetka utakmice u formatu YYYY-MM-DD HH:mm")]
                    //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
                    [Display(Name = "Poèetak utakmice: ")]
                    public System.DateTime PocetakUtakmice { get; set; }
                    public Nullable<int> golDomacin { get; set; }
                    public Nullable<int> golGost { get; set; }
                    public string rezultat { get; set; }
                    public string status { get; set; }
                    public string TipKraj { get; set; }
          }
}
